--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025. 05. 19. 8:35:41
-- Server version: 8.4.0
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8mb4';

--
-- Set default database
--
USE ugyfel;

--
-- Drop table `felhasznalo`
--
DROP TABLE IF EXISTS felhasznalo;

--
-- Set default database
--
USE ugyfel;

--
-- Create table `felhasznalo`
--
CREATE TABLE felhasznalo (
  id INT NOT NULL AUTO_INCREMENT,
  felhasznalo VARCHAR(100) NOT NULL,
  jelszo CHAR(64) NOT NULL,
  email VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_hungarian_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `felhasznalo` on table `felhasznalo`
--
ALTER TABLE felhasznalo 
  ADD UNIQUE INDEX felhasznalo(felhasznalo);

--
-- Create index `email` on table `felhasznalo`
--
ALTER TABLE felhasznalo 
  ADD UNIQUE INDEX email(email);

-- 
-- Dumping data for table felhasznalo
--
-- Table ugyfel.felhasznalo does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;